import { expect, test } from '@playwright/test';

const origin = `http://127.0.0.1:${process.env.FIREBIRD_PREFIX_SMOKE_PORT ?? '18766'}`;
const prefix = (process.env.NEXT_PUBLIC_BASE_PATH ?? '/firebird').replace(/\/+$/, '');

test('prefixed export loads bundles, library media, API and docs without escaping its mount', async ({ page }) => {
  const escaped: string[] = [];
  const failures: string[] = [];
  page.on('request', request => {
    const url = new URL(request.url());
    if (url.origin === origin && !url.pathname.startsWith(`${prefix}/`)) escaped.push(url.pathname);
  });
  page.on('response', response => {
    if (response.url().startsWith(origin) && response.status() >= 400) failures.push(`${response.status()} ${response.url()}`);
  });
  const project = await (await page.request.post(`${origin}${prefix}/api/v1/projects`, {data:{name:'Prefix import check'}})).json();
  await page.addInitScript(id=>localStorage.setItem('firebird.project',id),project.id);
  await page.goto(`${prefix}/`);
  await expect(page.getByRole('link', { name: 'Open Jensen workspace home' })).toHaveAttribute('href', `${prefix}/`);
  await expect(page.getByRole('button', { name: 'Fine-tune', exact: true })).toBeVisible();
  await page.getByRole('button', {name:'Create example',exact:true}).click();
  const poster = page.getByRole('region',{name:'Dataset labeling'}).getByRole('img');
  await expect(poster).toBeVisible();
  await expect(poster).toHaveAttribute('src',new RegExp(`^${prefix}/api/v1/datasets/`));
  await expect.poll(()=>poster.evaluate(node=>(node as HTMLImageElement).complete&&(node as HTMLImageElement).naturalWidth>0)).toBe(true);
  const download=page.getByRole('link',{name:'Export dataset'});
  await expect(download).toHaveAttribute('href',new RegExp(`^${prefix}/api/v1/datasets/`));
  expect((await page.request.get(origin+(await download.getAttribute('href')))).status()).toBe(200);
  await expect.poll(() => page.locator('.connection-notice').count()).toBe(0);
  await page.getByRole('button', { name: 'Cloud runs', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Cloud runs', exact: true, level: 1 })).toBeVisible();
  await expect(page.getByText('External rollout monitoring is not configured.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Dataset', exact: true }).click();
  const teachingState = page.waitForResponse(response => new URL(response.url()).pathname === `${prefix}/api/v1/teaching/state`);
  await page.getByRole('button', { name: 'Teaching', exact: true }).click();
  expect((await teachingState).status()).toBe(200);
  await expect(page.getByRole('heading', { name: 'Teaching', exact: true, level: 1 })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start recording', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Connect voice', exact: true })).toBeDisabled();
  const decisionState = page.waitForResponse(response => new URL(response.url()).pathname === `${prefix}/api/v1/decision/status`);
  await page.getByRole('button', { name: 'Decision lab', exact: true }).click();
  expect((await decisionState).status()).toBe(200);
  await expect(page.getByRole('region', { name: 'Decision advisory', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Teaching', exact: true }).click();
  await page.locator('.page-heading .page-guide').click();
  await expect(page).toHaveURL(new RegExp(`${prefix}/guide/#teaching$`));
  await expect(page.getByRole('heading', { name: 'Workspace guide', exact: true })).toBeVisible();
  await expect(page.locator('.guide-sections > section')).toHaveCount(13);
  await page.reload();
  await expect(page.locator('#teaching')).toContainText('Start recording');
  await page.getByRole('link', { name: 'API reference', exact: true }).first().click();
  await expect(page).toHaveURL(new RegExp(`${prefix}/docs/$`));
  await expect(page.getByRole('heading', { name: 'API reference', exact: true })).toBeVisible();
  await expect(page.getByText(origin + prefix + '/api/v1', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'OpenAPI JSON', exact: true })).toHaveAttribute('href', `${prefix}/openapi.json`);
  await expect(page.locator('.reference-endpoint')).not.toHaveCount(0);
  await page.locator('.reference-endpoint > summary').first().click();
  await expect(page.locator('.reference-example .reference-code').first()).toContainText(`${origin}${prefix}/`);
  await page.getByRole('link', { name: 'Back to workspace', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`${prefix}/$`));
  expect(escaped).toEqual([]);
  expect(failures).toEqual([]);
});
