/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Episodes */
        get: operations["list_episodes_api_v1_jobs__job_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/episodes/{episode_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Episode */
        get: operations["get_episode_api_v1_jobs__job_id__episodes__episode_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Dataset */
        post: operations["inspect_dataset_api_v1_projects__project_id__intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CameraPreview */
        CameraPreview: {
            /** End Seconds */
            end_seconds: number;
            /** Fps */
            fps: number;
            /** Height */
            height: number | null;
            /** Key */
            key: string;
            /** Start Seconds */
            start_seconds: number;
            /** Url */
            url: string;
            /** Width */
            width: number | null;
        };
        /**
         * Capability
         * @description Planned/untested records carry no support; outcome claims carry evidence.
         */
        Capability: {
            /** Description */
            description: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "dataset.inspect" | "dataset.inspect.local" | "policy.finetune" | "policy.distill" | "policy.quantize" | "policy.evaluate" | "policy.run";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Stage
             * @enum {string}
             */
            stage: "Dataset" | "Fine-tune" | "Distill" | "Quantize" | "Evaluate" | "Run";
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "untested" | "available" | "unsupported";
            /** Support */
            support?: components["schemas"]["CapabilitySupport"][];
        } & ({
            /** @enum {unknown} */
            status: "planned" | "untested";
            support?: unknown[];
        } | {
            /** @constant */
            status: "available";
            support: unknown[];
        } | {
            /** @constant */
            status: "unsupported";
            support: {
                /** @constant */
                evidence_state: "unsupported";
            }[];
        });
        /**
         * CapabilityEvidence
         * @description Reference to reviewed evidence; validation does not execute or verify it.
         */
        CapabilityEvidence: {
            /** Device Name */
            device_name: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Reference */
            reference: string;
            /** Runtime */
            runtime: string;
            /** Source Revision */
            source_revision: string;
        };
        /**
         * CapabilitySupport
         * @description Evidence for one parent operation on one concrete execution target.
         */
        CapabilitySupport: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "metadata" | "lerobot" | "openvla_oft";
            /**
             * Device
             * @enum {string}
             */
            device: "cpu" | "cuda";
            /** Evidence */
            evidence: components["schemas"]["CapabilityEvidence"][];
            /**
             * Evidence State
             * @enum {string}
             */
            evidence_state: "tested" | "unsupported";
            /**
             * Os
             * @enum {string}
             */
            os: "linux" | "windows" | "macos";
        };
        /** DatasetProfile */
        DatasetProfile: {
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /**
             * Format
             * @enum {string}
             */
            format: "lerobot_v2" | "lerobot_v3";
            /** Fps */
            fps: number;
            /**
             * Inspected At
             * Format: date-time
             */
            inspected_at: string;
            /**
             * Inspection Scope
             * @default metadata_only
             * @enum {string}
             */
            inspection_scope: "metadata_only" | "bounded_parquet_rows";
            /** License */
            license?: string | null;
            /** Metadata Sha256 */
            metadata_sha256: string;
            preview?: components["schemas"]["LocalDatasetPreview"] | null;
            /** Repo Id */
            repo_id?: string | null;
            /** Revision */
            revision: string;
            /** Robot Type */
            robot_type?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Source
             * @enum {string}
             */
            source: "huggingface" | "local";
            /** Total Episodes */
            total_episodes: number;
            /** Total Frames */
            total_frames: number;
            /** Warnings */
            warnings: string[];
        };
        /** EpisodePage */
        EpisodePage: {
            /** Episodes */
            episodes: components["schemas"]["EpisodeSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Repo Id */
            repo_id: string;
            /** Revision */
            revision: string;
            /** Total Episodes */
            total_episodes: number;
            /** Warnings */
            warnings: string[];
        };
        /** EpisodePreview */
        EpisodePreview: {
            /** Action Names */
            action_names: string[];
            /** Cameras */
            cameras: components["schemas"]["CameraPreview"][];
            /** Duration Seconds */
            duration_seconds: number;
            /** Episode Index */
            episode_index: number;
            /** Frame Count */
            frame_count: number;
            /** Repo Id */
            repo_id: string;
            /** Revision */
            revision: string;
            /** Samples */
            samples: components["schemas"]["FrameSample"][];
            /** State Names */
            state_names: string[];
            /** Tasks */
            tasks: string[];
            /** Warnings */
            warnings: string[];
        };
        /** EpisodeSummary */
        EpisodeSummary: {
            /** Duration Seconds */
            duration_seconds: number;
            /** Episode Index */
            episode_index: number;
            /** Frame Count */
            frame_count: number;
            /** Tasks */
            tasks: string[];
        };
        /** FrameSample */
        FrameSample: {
            /** Action */
            action: number[] | null;
            /** Frame Index */
            frame_index: number;
            /** State */
            state: number[] | null;
            /** Timestamp */
            timestamp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeRequest */
        IntakeRequest: {
            /** Path */
            path?: string | null;
            /** Repo Id */
            repo_id?: string | null;
            /**
             * Revision
             * @default main
             */
            revision: string;
            /**
             * Source
             * @default huggingface
             * @enum {string}
             */
            source: "huggingface" | "local";
        };
        /** Job */
        Job: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @default dataset.inspect
             * @constant
             */
            kind: "dataset.inspect";
            /** Project Id */
            project_id: string;
            request: components["schemas"]["IntakeRequest"];
            result?: components["schemas"]["DatasetProfile"] | null;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        JsonValue: unknown;
        /** LocalDatasetPreview */
        LocalDatasetPreview: {
            /** Columns */
            columns: string[];
            /** Declared Decoded Bytes */
            declared_decoded_bytes: number;
            file: components["schemas"]["LocalPreviewFile"];
            /**
             * Format
             * @default lerobot_v3
             * @constant
             */
            format: "lerobot_v3";
            /**
             * Inspection Scope
             * @default bounded_parquet_rows
             * @constant
             */
            inspection_scope: "bounded_parquet_rows";
            /**
             * Kind
             * @enum {string}
             */
            kind: "frames" | "episodes";
            limits: components["schemas"]["LocalPreviewLimits"];
            /** Metadata Sha256 */
            metadata_sha256: string;
            /** Omitted Columns */
            omitted_columns: string[];
            /**
             * Preview Schema Version
             * @default 1
             * @constant
             */
            preview_schema_version: 1;
            /** Read Bytes */
            read_bytes: number;
            /**
             * Reader
             * @constant
             */
            reader: "pyarrow==25.0.1";
            /** Returned Rows */
            returned_rows: number;
            /**
             * Row Offset
             * @default 0
             * @constant
             */
            row_offset: 0;
            /** Rows */
            rows: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /**
             * Source
             * @default local
             * @constant
             */
            source: "local";
            /** Total File Rows */
            total_file_rows: number;
            /** Truncated */
            truncated: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** LocalPreviewFile */
        LocalPreviewFile: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** LocalPreviewLimits */
        LocalPreviewLimits: {
            /**
             * Max Decoded Bytes
             * @default 8388608
             */
            max_decoded_bytes: number;
            /**
             * Max File Bytes
             * @default 4194304
             */
            max_file_bytes: number;
            /**
             * Max Output Bytes
             * @default 65536
             */
            max_output_bytes: number;
            /**
             * Max Read Bytes
             * @default 16777216
             */
            max_read_bytes: number;
            /**
             * Max Rows
             * @default 10
             */
            max_rows: number;
            /**
             * Timeout Seconds
             * @default 10
             */
            timeout_seconds: number;
        };
        /** Project */
        Project: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_api_v1_jobs__job_id__episodes_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_api_v1_jobs__job_id__episodes__episode_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                episode_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_dataset_api_v1_projects__project_id__intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_projects__project_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
