/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Options */
        get: operations["policy_options_api_v1_policy_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v1_projects__project_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_projects__project_id__artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Dataset */
        post: operations["inspect_dataset_api_v1_projects__project_id__intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/policy-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Policy Job */
        post: operations["policy_job_api_v1_projects__project_id__policy_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Capability
         * @description Application availability plus separately scoped support evidence.
         *
         *     Explicit empty support denotes unknown target coverage, not tested support.
         *     Callers must supply the field; CAP-001 must populate reviewed target records.
         */
        Capability: {
            /** Description */
            description: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "dataset.inspect" | "dataset.inspect.local" | "policy.finetune" | "policy.distill" | "policy.quantize" | "policy.evaluate" | "policy.run";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Stage
             * @enum {string}
             */
            stage: "Dataset" | "Fine-tune" | "Distill" | "Quantize" | "Evaluate" | "Run";
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "planned";
            /** Support */
            support: components["schemas"]["CapabilitySupport"][];
        };
        /**
         * CapabilityEvidence
         * @description Reference to reviewed evidence; validation does not execute or verify it.
         */
        CapabilityEvidence: {
            /** Device Name */
            device_name: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Reference */
            reference: string;
            /** Runtime */
            runtime: string;
            /** Source Revision */
            source_revision: string;
        };
        /**
         * CapabilitySupport
         * @description Evidence for one parent operation on one concrete execution target.
         */
        CapabilitySupport: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "metadata" | "lerobot" | "openvla_oft" | "vla_cpp";
            /**
             * Device
             * @enum {string}
             */
            device: "cpu" | "cuda";
            /** Evidence */
            evidence?: components["schemas"]["CapabilityEvidence"][];
            /**
             * Evidence State
             * @enum {string}
             */
            evidence_state: "planned" | "untested" | "tested" | "unsupported";
            /**
             * Os
             * @enum {string}
             */
            os: "linux" | "windows" | "macos";
        };
        /** DatasetProfile */
        DatasetProfile: {
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /**
             * Format
             * @enum {string}
             */
            format: "lerobot_v2" | "lerobot_v3";
            /** Fps */
            fps: number;
            /**
             * Inspected At
             * Format: date-time
             */
            inspected_at: string;
            /**
             * Inspection Scope
             * @default metadata_only
             * @constant
             */
            inspection_scope: "metadata_only";
            /** License */
            license?: string | null;
            /** Metadata Sha256 */
            metadata_sha256: string;
            /** Repo Id */
            repo_id?: string | null;
            /** Revision */
            revision: string;
            /** Robot Type */
            robot_type?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Source
             * @enum {string}
             */
            source: "huggingface" | "local";
            /** Total Episodes */
            total_episodes: number;
            /** Total Frames */
            total_frames: number;
            /** Warnings */
            warnings: string[];
        };
        /** Evaluation */
        Evaluation: {
            /** Final States */
            final_states?: number[];
            /** Initial States */
            initial_states?: number[];
            /**
             * Mode
             * @default engine
             * @enum {string}
             */
            mode: "engine" | "libero";
            /**
             * Repetitions
             * @default 10
             */
            repetitions: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Steps
             * @default 500
             */
            steps: number;
            /**
             * Task Id
             * @default 0
             */
            task_id: number;
            /**
             * Warmups
             * @default 3
             */
            warmups: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeRequest */
        IntakeRequest: {
            /** Path */
            path?: string | null;
            /** Repo Id */
            repo_id?: string | null;
            /**
             * Revision
             * @default main
             */
            revision: string;
            /**
             * Source
             * @default huggingface
             * @enum {string}
             */
            source: "huggingface" | "local";
        };
        /** Job */
        Job: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @default dataset.inspect
             */
            kind: string;
            /** Project Id */
            project_id: string;
            /** Request */
            request: components["schemas"]["IntakeRequest"] | components["schemas"]["PolicyRequest"];
            /** Result */
            result?: components["schemas"]["DatasetProfile"] | components["schemas"]["LifecycleResult"] | null;
            /** Stage */
            stage?: string | null;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobEvent */
        JobEvent: {
            /** Message */
            message: string;
            /** Sequence */
            sequence: number;
            /** Stage */
            stage: string;
            /** Timestamp */
            timestamp: string;
        };
        /** LifecycleResult */
        LifecycleResult: {
            /** Artifacts */
            artifacts?: components["schemas"]["PolicyArtifact"][];
            /**
             * Decision
             * @default completed
             * @enum {string}
             */
            decision: "completed" | "diagnostics_only" | "no_feasible_candidate" | "validated";
            /** Reports */
            reports?: {
                [key: string]: unknown;
            }[];
            /** Selected Artifact Id */
            selected_artifact_id?: string | null;
        };
        /** Limits */
        Limits: {
            /**
             * Max P95 Ms
             * @default 1000
             */
            max_p95_ms: number;
            /**
             * Max Peak Device Mib
             * @default 8192
             */
            max_peak_device_mib: number;
            /**
             * Max Success Drop
             * @default 0
             */
            max_success_drop: number;
            /**
             * Min Success Rate
             * @default 1
             */
            min_success_rate: number;
        };
        /** PolicyArtifact */
        PolicyArtifact: {
            /** File Bytes */
            file_bytes: number;
            /**
             * Format
             * @enum {string}
             */
            format: "gguf" | "training_checkpoint" | "native_checkpoint" | "deployment_package";
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Label */
            label: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Parent Ids */
            parent_ids?: string[];
            /** Path */
            path: string;
            /** Project Id */
            project_id: string;
        };
        /** PolicyRequest */
        PolicyRequest: {
            /** Artifact Id */
            artifact_id?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["Precision"][];
            /** Dataset Job Id */
            dataset_job_id?: string | null;
            evaluation?: components["schemas"]["Evaluation"];
            limits?: components["schemas"]["Limits"] | null;
            /**
             * Operation
             * @enum {string}
             */
            operation: "policy.import" | "policy.finetune" | "policy.export" | "policy.quantize" | "policy.evaluate" | "policy.run" | "policy.workflow";
            precision?: components["schemas"]["Precision"] | null;
            /** Resume Job Id */
            resume_job_id?: string | null;
            /** Runtime Id */
            runtime_id: string;
            /** Source Id */
            source_id?: string | null;
            /**
             * Timeout Seconds
             * @default 7200
             */
            timeout_seconds: number;
            /** Training */
            training?: {
                [key: string]: unknown;
            } | null;
            /**
             * Training Method
             * @default lora
             */
            training_method: string;
        };
        /** Precision */
        Precision: {
            /**
             * Language
             * @default Q4_0
             * @enum {string}
             */
            language: "Q4_0" | "Q8_0";
            /** Vision */
            vision?: "Q8_0" | null;
        };
        /** Project */
        Project: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_options_api_v1_policy_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifacts_api_v1_projects__project_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyArtifact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_projects__project_id__artifacts__artifact_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_dataset_api_v1_projects__project_id__intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_projects__project_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_job_api_v1_projects__project_id__policy_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
